### ISSUE TITLE
 مناسبت‌های اقوام یا شهرهای خاص

### ISSUE THREAD

**Issue by dariubs** [persiancal/cal-events#10]
در مورد  مناسب‌های مخصوص یک قوم یا شهر که شاید در تقویم رسمی ذکر نشده باشند ولی در یک منطقه وجود داره هم بنظرم میشه برنامه‌ داشت.

مثلا قزوینی ها یه مراسمی دارن به اسم پنجاه بدر که هنوز برگزار میشه ولی خب شاید تو شهر دیگه‌ای نباشه.

https://fa.wikipedia.org/wiki/%D9%BE%D9%86%D8%AC%D8%A7%D9%87_%D8%A8%D8%AF%D8%B1

**Comment by fzerorubigd** [comment]
برای این پیشنهاد من استفاده از کلید 
calendar 
است. 
برای این رویدادها یک تایپ مشخص درنظر میگیریم، مثلا رویدادهای شهر قزوین در این مورد. لیستی از این موارد در نهایت اهست که کاربر میتونه بر اساس اون لیست فیلتر کنه رویدادهایی که میخواد.

**Comment by fzerorubigd** [comment]
فکر میکنم شکل فعلی کلید 
calendar 
پاسخگوی این نیاز باشه. من این ایشو رو میبندم اگر به نظرتون نیازه مجددا بازش کنید یا اینکه یه ایشوی جدید درست کنید

ممنون!
