### ISSUE TITLE
شیوه بهتری برای اعتبارسنجی منابع

### ISSUE THREAD

**Issue by okian** [persiancal/cal-events#104]
ویکیپدیا در هر صورت و با برای آدرسی ۲۰۰ برمیگردنه و عملا شیوه فعلی کاربردی نداره
نمونه:
[https://fa.wikipedia.org/wiki/ضصثقفصفخحنزطتترپظکطدتدظ](https://fa.wikipedia.org/wiki/ضصثقفصفخحنزطتترپظکطدتدظ)

**Comment by fzerorubigd** [comment]
من چک کردم و اینطور نیست. براش هم یه تست نوشتم.
فکر میکنم وقتی با 
browser 
میری ریدایرکتت میکنه به اینجا.
