### ISSUE TITLE
ماههای میلادی

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#116]
مقدمات برای شروع ماههای میلادی. 
البته بهتره صبر کنیم برای #35 تا به سرانجام برسه بعد شروع کنیم. 

- اسم تقویم چی باشه؟
-  آیا ترجمه انگلیسی هم اضافه کنیم بهش؟ به نظر من ممکنه مشارکت رو سخت کنه، ولی خب بالاخره باید اینها اضافه بشن.

**Comment by okian** [comment]
gregorian?

**Comment by fzerorubigd** [comment]
در مورد انتخاب اسم، من اسم جلالی رو انتخاب کردم برای هجری شمسی که ظاهرا درست نیست. 
بهتره دقیقا رفرنس پیدا کنیم که این درسته :)

**Comment by okian** [comment]
بهتر نیست قبل از تقویم میلادی تقویم بین‌المللی رو انجام بدیم که خیلی از رویدادهاش هم توسط بخش بزرگی از جامعه و نظام پذیرفته شده (روزهای کودک٬ کارگر٬ زمین٬ خبرنگار ...) و بخش بزرگتری از جامعه  باهاش کار دارند؟
[https://www.un.org/en/sections/observances/international-days](https://www.un.org/en/sections/observances/international-days/)

**Comment by fzerorubigd** [comment]
منظور من از تقویم میلادی، تقویمیه که ماههای میلادی رو توی خودش داره.
بین‌الملل میشه یه
Calendar
توی اون.
