### ISSUE TITLE
افزودن رویدادهای مرتبط به ماههای میلادی

### ISSUE THREAD

**Issue by hramezani** [persiancal/cal-events#129]
این تیکت به عنوان راهنمای برای ماه های میلادی استفاده میشه.
اگر مشکلی یا سوالی بود اینجا مطرح بشه

**Comment by srahnama** [comment]
`calendar `
 رو چی باید بنویسیم؟
همون 
`Iran Official`

**Comment by okian** [comment]
این فایل رو ببین
https://github.com/persiancal/cal-events/blob/master/gregorian/preset.yml

**Comment by fzerorubigd** [comment]
با توجه به اینکه سورس این تقویم انگلیسیه، لطفا برای عنوان و توضیحات کلید 
en_US 
رو هم پر کنید، تر جمه فارسی رو هم حتما اضفه کنید.

**Comment by srahnama** [comment]
en_US
این رو اضافه کردم
و اینکه اگه سورس فارسی و انگلیسی داشت هر دو رو قرار میدم

**Comment by sbabashahi** [comment]
رویدادهایی که در تاریخ مشخصی نیستند و براساس روز چندم هفته  یا غیره بدست میان رو چجوری باید مشخص کرد؟ مثل
7 October (first Monday in October)

World Habitat Day  (A/RES/40/202 A)

20 October (every five years, beginning in 2010)

World Statistics Day (A/RES/69/282)

**Comment by fzerorubigd** [comment]
@sbabashahi این مساله از اول هم بوده و هنوز حلش نکردیم 
اینجا https://github.com/persiancal/cal-events/issues/8

**Comment by rminix** [comment]
برای روز وساک که مربوط به بودایی ها است،  میشه از 
Buddhist
توی
calendar
استفاده کرد?

**Comment by fzerorubigd** [comment]
<div dir="rtl">
بله به نظرم میشه به تقویم میلادی اضافش کرد. 
یه فایل `preset.yml` هست که باید تقویم اونجا باشه تا توی تست ها گیر نده. اونجا هم اضافش کنید، اگر هم نمیتونید بگید که ما اضافه کنیم. 
</div>

**Comment by rminix** [comment]
نه مشکلی نیست، حتما اضافش می‌کنم.

**Comment by okian** [comment]
من چک کردم در قطعنامه سازمان ملل این به عنوان <روزه ماه کامل> یاد شده٬ درسته به احترام بودایی‌ها است اما به نظرم روز‌ بین المللی است مثل نوروز
نکته دیگه اینکه این روز هم به #8 وابسته است چون در قطعنامه تاریخ دقیق نداره و گفته شده روزی در ماه مه که ماه کامل است (معادل ۱۵ ماه قمری) و خوب چنین روزی تاریخ دقیق نداره.

ٰhttps://www.un.org/en/ga/search/view_doc.asp?symbol=A/RES/54/115

**Comment by fzerorubigd** [comment]
در مورد نوروز، نه، چون نوروز رسما یک رویداد تقویم جلالیه و قبلا اضافه شده. در مورد روز زبان فرانسه، این روز اگر مرتبط به فرانسه باشه جاش تو این تقویم نیست، مگر اینکه بین المللی باشه که خب قبلا داریمش

**Comment by hramezani** [comment]
ممنون از همه که زحمت ماه های میلادی رو کشیدن.
