### ISSUE TITLE
ماه ژوئن، تقویم میلادی

### ISSUE THREAD

**Issue by hramezani** [persiancal/cal-events#135]
[مستندات](https://github.com/persiancal/cal-events/blob/master/docs/events.md) مربوط به کلیدهای رویداد را ببینید

و اگر سوالی داشتید هم برای اینکه یکجا باشد در ایشوی شماره #129  بپرسید

رویداد ها رو هم میتونید از [اینجا](https://www.un.org/en/sections/observances/international-days/) ببینید

**Comment by irajtaghlidi** [comment]
بعد مطالعه آپدیت ایشو ها فردا این رو شروع می‌کنم.

**Comment by fzerorubigd** [comment]
@irajtaghlidi friendly ping :D

**Comment by irajtaghlidi** [comment]
> @irajtaghlidi friendly ping :D

PONG!
متاسفانه هفته شلوغی بود نشد بشینم کامل‌اش کنم تازه اوایلشم. اگر صلاح هست به شخص دیگه ای واگذار بشه. (گاها مایلستون رو نگاه می‌کردم ببینم چقدر عقبم :) ) ولی فرصت باشه خودم تکمیل‌اش می‌کنم.
اکانت گیت‌هاب هم بلاک شد هرچند به پابلیک ها دسترسی دارم ولی گفتم بهتر اول وریفای اش کنم تا گیر به کل اورگانایزیشن نده.

**Comment by amin3mej** [comment]
اگر @irajtaghlidi تمایل داشته باشید، من می‌تونم این‌کار رو انجام بدم.

**Comment by fzerorubigd** [comment]
فکر کنم قبلا هم گفتن که مشکلی نداره.

**Comment by irajtaghlidi** [comment]
سلام مجدد.
اگر لطف کنی ممنون می‌شم. خودم ناراحت هستم که قبول کردم و نشد سر وقت برسونم.
