### ISSUE TITLE
ماه ژوئیه، تقویم میلادی

### ISSUE THREAD

**Issue by hramezani** [persiancal/cal-events#136]
[مستندات](https://github.com/persiancal/cal-events/blob/master/docs/events.md) مربوط به کلیدهای رویداد را ببینید

و اگر سوالی داشتید هم برای اینکه یکجا باشد در ایشوی شماره #129  بپرسید

رویداد ها رو هم میتونید از [اینجا](https://www.un.org/en/sections/observances/international-days/) ببینید

**Comment by Goudarz** [comment]
من اینم انجام میدم

**Comment by fzerorubigd** [comment]
برای اینکه خیلی سخت نشه پیگیریش، یکی یکی انجام بدین که ما هم بتونیم پیگیریش کنیم.

**Comment by saeedghx68** [comment]
اگه اوکی هست من میتونم روز به روز بفرستم که پیگیریش هم راحت باشه براتون؟

**Comment by saeedghx68** [comment]
من میتونم انجام بدم اگه مشکلی نداره!؟

**Comment by fzerorubigd** [comment]
@saeedghx68 friendly ping :D
