### ISSUE TITLE
ماه اوت، تقویم میلادی

### ISSUE THREAD

**Issue by hramezani** [persiancal/cal-events#137]
[مستندات](https://github.com/persiancal/cal-events/blob/master/docs/events.md) مربوط به کلیدهای رویداد را ببینید

و اگر سوالی داشتید هم برای اینکه یکجا باشد در ایشوی شماره #129  بپرسید

رویداد ها رو هم میتونید از [اینجا](https://www.un.org/en/sections/observances/international-days/) ببینید

**Comment by sbabashahi** [comment]
من انجام میدم

**Comment by okian** [comment]
ممنون😉
fixed #149
