### ISSUE TITLE
ماه نوامبر، تقویم میلادی

### ISSUE THREAD

**Issue by hramezani** [persiancal/cal-events#140]
[مستندات](https://github.com/persiancal/cal-events/blob/master/docs/events.md) مربوط به کلیدهای رویداد را ببینید

و اگر سوالی داشتید هم برای اینکه یکجا باشد در ایشوی شماره #129  بپرسید

رویداد ها رو هم میتونید از [اینجا](https://www.un.org/en/sections/observances/international-days/) ببینید

**Comment by amin3mej** [comment]
این رو لطفا به من اساین کنید.

**Comment by amin3mej** [comment]
برای این ماه، تو رویداد با وضعیت نسبی وجود دارند.
اینجا می‌نویسم که بعدش زمانی #8 حل شد، این رو اصلاح کنم.

(اگه نیاز به یک ایشیو دیگه منتقل بشه، بفرمایید تا منتقل کنم.)

**Comment by fzerorubigd** [comment]
fixed in #158
