### ISSUE TITLE
ماه دسامبر، تقویم میلادی

### ISSUE THREAD

**Issue by hramezani** [persiancal/cal-events#141]
[مستندات](https://github.com/persiancal/cal-events/blob/master/docs/events.md) مربوط به کلیدهای رویداد را ببینید

و اگر سوالی داشتید هم برای اینکه یکجا باشد در ایشوی شماره #129  بپرسید

رویداد ها رو هم میتونید از [اینجا](https://www.un.org/en/sections/observances/international-days/) ببینید

**Comment by neda1985** [comment]
من انجام میدم اساین کنید لطفا

**Comment by fzerorubigd** [comment]
@neda1985 friendly ping :D

**Comment by neda1985** [comment]
@fzerorubigd امشب حتما کامل میکنم

**Comment by neda1985** [comment]
اقا من یه سوالی دارم برای این اونت ها هم سالهاشون مهمه؟ مثلا برای روز جهانی ایدز که از سال۱۹۸۸ شروع کردن این الان سال این اینونت میشه؟

**Comment by fzerorubigd** [comment]
بله، سالی که معرفی شده،‌میشه سال اون رویداد/مناسبت.

**Comment by neda1985** [comment]
مناسبت هایی که لینک ویکی نداره چی میشه؟

**Comment by okian** [comment]
> @fzerorubigd
> مناسبت هایی که لینک ویکی نداره چی میشه؟

اگر در تقویم سازمان ملل هست مهم نیست که لینک ویکی نداشته باشه

**Comment by neda1985** [comment]
@okian
 پس لینک خود سازمان ملل و بزاریم؟ با خالی باشه؟

**Comment by fzerorubigd** [comment]
خالی باشه. فعلا فقط لینک ویکی‌پدیا رو باید اضافه کنید.
