### ISSUE TITLE
دیتا هارو از پروژه زبان گو جدا کنید

### ISSUE THREAD

**Issue by mhf-ir** [persiancal/cal-events#152]
به نظرم یه ریپوزیتوری گیت کافی هست یا میشه یه ریپوزیتوری ان پی ام براش ساخت.
مثل:
https://github.com/unicode-cldr/cldr-core

ممنون بابت زحماتتون.

**Comment by fzerorubigd** [comment]
دیتا از پروژه گو جدا هست، دیتایی که شما میخواید اینجاست 

https://github.com/persiancal/cal-events/tree/gh-pages
