### ISSUE TITLE
رویداد های مهم بدون صفحه مستقل ویکی پدیا 

### ISSUE THREAD

**Issue by tavallaie** [persiancal/cal-events#161]
<div dir="rtl">
تقویم رویداد مشکل‌دار/ناقص :‌ 
ماه رویداد : ۰۸ 
روز رویداد:‌ ۱۱ 
مشکل رویداد : صفحه ویکیپدیای ناقص 
روز جوان یک رویداد ملی هست که بر اساس رویداد تولد علی اکبر در تقویم جمهوری اسلامی تعریف شده ولی صفحه ویکی مستقل ندارد، این رویداد ها رو به کجا منبع بدیم؟ 

اگر این رویداد یک رویداد جدید است، یا لینک منبع ندارد، حتما لینک ویکی پدیا را اضافه کنید :‌

</div>

**Comment by okian** [comment]
اگر در تقویم رسمی است فیلد منبع میتونه خالی باشه
