### ISSUE TITLE
ماه مرداد تقویم جلالی

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#17]
Ref #11

**Comment by dariubs** [comment]
این ماه رو من انجام میدم

**Comment by dariubs** [comment]
سه تا از مناسبتها رو حذف کردم ولی برای خودم نگه داشتم تا در مورد روزشون مطمئن بشیم و دوباره اضافه بکنیم: 

جشن چله تابستان
جشن میانه تابستان
جشن میخواره

و یکی از مناسبتها هم به نظر خیلی رسمی نمیاد یا من درست منبعی پیدا نکردم تو منابع رسمی براش که موقتا حذف کردم:

روز حقوق بشر اسلامی و کرامت انسانی
