### ISSUE TITLE
ماه شهریور تقویم جلالی

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#18]
Ref #11

**Comment by sbabashahi** [comment]
این ماه رو من انجام میدم

**Comment by hramezani** [comment]
ممنون! لطفا این ایشو رو هم دنبال کنید 

https://github.com/persiancal/cal-events/issues/11 

برای اینکه سوالات یکجا باشن، اونجا اگه سوالی داشتید بپرسید.
