### ISSUE TITLE
ماه آذر تقویم جلالی

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#21]
Ref #11

**Comment by amirnaderi** [comment]
این ماه رو من انجام میدم

**Comment by fzerorubigd** [comment]
ممنون! لطفا این ایشو رو هم دنبال کنید 

https://github.com/persiancal/cal-events/issues/11 

برای اینکه سوالات یکجا باشن، اونجا اگه سوالی داشتید بپرسید.

**Comment by amirnaderi** [comment]
سلام من نمی تونم برنچ که ساختم رو پوش کنم، فکر کنم دسترسی ندارم

**Comment by fzerorubigd** [comment]
میتونید فورک کنید و روی فورک پوش کنید. ممنون بابت لطفی که میکنید!
