### ISSUE TITLE
ماه دی تقویم جلالی

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#22]
Ref #11

**Comment by neda1985** [comment]
این برای من

**Comment by neda1985** [comment]
@fzerorubigd من این ایشو رو تموم کردم و دوستان هم ریویو کردن فکر کنم بشه مرجش کرد 
https://github.com/persiancal/cal-events/pull/50

**Comment by fzerorubigd** [comment]
ممنون!
من جنریت میکنم و پوش میکنم روی برنچ شما که تست پس شه و بعد مرج میکنیم.

**Comment by fzerorubigd** [comment]
fixes #50
