### ISSUE TITLE
ساختار پوشه‌ها

### ISSUE THREAD

**Issue by okian** [persiancal/cal-events#26]
ساختار پوشه‌ها رو اینطور در نظر بگیریم که پوشه تقویم داشته باشیم و برای هم تقویم یک پوشه و داخلش برای هر ماه یک فایل.

اینطور هم کمتر کانفلیکت به وجود میاد و فایل‌ها کوچکتر مشین و کار باهاشون راحت‌تر.
مثلا:

calendars
├── hijri
│  ├── 1.yaml  # moharam
│  ├── 2.yaml
│  ├── 3.yaml
│  ├── 4.yaml
│  ├── 5.yaml
│  ├── 6.yaml
│  ├── 7.yaml
│  ├── 8.yaml
│  ├── 9.yaml
│  ├── 10.yaml
│  ├── 11.yaml
│  └── 12.yaml
└── jalali
   ├── 1.yaml # farvardin
   ├── 2.yaml
   ├── 3.yaml
   ├── 4.yaml
   ├── 5.yaml
   ├── 6.yaml
   ├── 7.yaml
   ├── 8.yaml
   ├── 9.yaml
   ├── 10.yaml
   ├── 11.yaml
   └── 12.yaml

**Comment by fzerorubigd** [comment]
من موافقم، ولی به نظر اسم اینجوری باشه

1-farvardin.yaml

عدد برای ترتیب باشه ولی برای خوانایی اسم هم کنارش باشه، منتها برای تعیین اعتبار اسم مهم نیست

**Comment by okian** [comment]
برای هر زبان هم پوشه مجزا داشته باشیم؟

**Comment by neda1985** [comment]
به نظر من  بهتره که اگه بعد کسی خواست زبون دیگه اضافه کنه راحتتره

**Comment by fzerorubigd** [comment]
اگر کلیدها رو چک کنید، همه کلید ها چند زبانه هستن به این شکل

Title:
  fa_IR: توضیح فارسی
  en_US: title


جدا کردن اینها توی فایلهای مختلف، نگهداری رو سخت میکنه، و اینکه یه زبان رو
باید رفرنس کنیم (برای تعیین اعتبار) که کار رو سخت میکنه.

**Comment by fzerorubigd** [comment]
اگه لطفا پول ریکوئست من رو بررسی کنید و ریویو، فکر کنم نتیجه همونیه که میخوایم
