### ISSUE TITLE
README

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#29]
ویرایش فایل برای اضافه کردن ساختار و توضیح هر بخش و طریقه اعتبار سنجی و ویرایش

**Comment by dariubs** [comment]
<div dir="rtl">
برای راست به چپ نوشتن متن مارک داون در فایل ریدمی بجای اینکه همه متن رو اچ تی ام ال کنیم میتونیم متن مارک داون رو داخل تگ اچ تی ام ال راست به چپ بزاریم مثل همین کامنت.

</div>

```html
<div dir="rtl">
markdown content
</div>
```

**Comment by fzerorubigd** [comment]
ممنون، ولی اون readme تموم شده دورانش و یه توضیح کاملتر لازمه. که ساختار رو توضیح بده.

**Comment by dariubs** [comment]
اینو به این خاطر فرستادم که ساختار کلی ریدمی فایل اگر قراره فارسی نوشته بشه قدری مرتب‌تر و خواناتر و ادیتبل تر باشه

**Comment by fzerorubigd** [comment]
به نظر من کلیتش اوکیه، حالا که شروع کردی چرا ادامش نمیدی؟ :) توضیح درباره ساختار و همه چی

**Comment by dariubs** [comment]
ردیفش میکنم :)

**Comment by fzerorubigd** [comment]
با توجه به اینکه خیلی سریعتر از اونچیزی که فکر میکردم این کار پیش رفت، این 
README 
خیلی بیشتر نیازه برای پاسخ دادن به یک سری سوالها. 
@persiancal/cal-events-reviewer 
کسی داوطلب میشه برای همین یکی دو روزه؟

**Comment by sbabashahi** [comment]
اگه بتونید توضیح بدید که چه کار هایی بکنم و من بتونم خوشحال میشم کمک کنم

**Comment by fzerorubigd** [comment]
این فایل ویترین این رپوزیتوریه. توضیحات لازم داره بعلاوه اینکه هدف چیه و چجوری میشه کمک کرد
