### ISSUE TITLE
اعتبار سنجی

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#3]
چگونه باید به یک رویداد اعتبار داد. مثلا اگر من معتقد باشم تولد من مهمه باید اینجا باشه چی؟ البته برای مرگها و تولدها یه ساختار دیگه بعدا اضافه میشه. 
مثلا اگر پیروان یک مکتب خاص بخوان رویدادهاشونو اضافه کنن مبنای رد یا تایید رو چی بذاریم؟

 پیشنهاد اولیه من اینه که مبنای اعتبار یک رویداد رو بذاریم ویکی پدیا یا منابع رسمی یک کشور. هر کدوم بود اون رویداد رو بپذیریم

**Comment by sajadghorbanii** [comment]
میشه گذاشت هر رویدادی ثبت بشه و وضعیت تاییده شده یا نبودنش مشخص بشه اینطوری امکانش هست سازوکاراعتبار سنجی هم اضافی بشه که اگه کسی خواست مشارکت کنه برای تایید معتبر بودن یک ادعا مدارک ارائه کنه و روند تایید مجددا طی بشه.
برای معتبر بودن هم میشه درجه اعتبار تعریف کرد فرضا منابع رسمی و کشوری و غیر کشوری مثلا 5 ویکی 4 وبسایت های و وبلاگ‌های سابقه‌دار 3 و در نهابت تایید نشده‌ها هم صفر.

**Comment by fzerorubigd** [comment]
اضافه شدن هر رویدادی یکم زیاده رویه. جمع کردنش سخت میشه. ولی برای روش اعتبار سنجی موافقم، اینکه یه 
enum 
تعریف بشه براش، البته نه به صورت عددی، بیشتر یه رشته به عنوان منبع تایید. مثل 
Wikipedia, IranOfficial, AfghanistanOfficial , ...

**Comment by fzerorubigd** [comment]
به نظر میاد که این قضیه به صورت دیگه در 
#35 حل شده. میشه بستش.
