### ISSUE TITLE
Validate source url

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#32]
برای تعیین اعتبار لینکهای درج شده به عنوان منبع، تنها کاری که به نظرم میرسه اینه که همه رو چک کنیم که خروجیش ۲۰۰ باشه و نه ریدایرکت یا هر کد دیگه‌ای. 
فقط نمیدونم ویکی بلاکمون میکنه یا نه :)

**Comment by okian** [comment]
فکر کنم باید دستی چک بشه چون لزوما فقط ویکی نیست و امکان داره با رنج ۳۰۰ جواب بده ولی اگر. مخصوصا که برای http به https.
ولی بعید میدونم اگر بین هر درخواست بیش از ۲۰۰ میلی‌ثانیه فاصله باشه بلاک کنه.

**Comment by fzerorubigd** [comment]
اتفاقا رنج ۳۰۰ یعنی اشتباه. اگه ۳۰۰ بگیریم باید درست کنیم لینک رو به صفحه اصلی. هدف من یکیش اینه که جلوی این ریدایرکت گرفته شه.
