### ISSUE TITLE
Check for unique key on all generated files

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#37]

**Comment by okian** [comment]
Already done. 7419049

**Comment by fzerorubigd** [comment]
این کل کلیدهای جنریت شده نیست، صرفا کلیدهای یک فایل به خصوصه. برای همشون یه ابرار لازمه که احتمالا همه کلیدهای نهایی رو چک کنه

**Comment by okian** [comment]
این رو بعد از بسته شدن #35 ادامه میدم.

**Comment by fzerorubigd** [comment]
فکر میکنم میشه الان این رو انجام داد.
