### ISSUE TITLE
Update dist directory on release tags

### ISSUE THREAD

**Issue by okian** [persiancal/cal-events#48]
از آنجایی که خیلی‌ها با زبان گو آشنایی ندارند به نظرم پوشه دیست رو خودمون/سی‌آی به صورت مجزا به روز کنیم بهتر باشه.

**Comment by fzerorubigd** [comment]
<div dir="rtl">
یه مشکلی که هست اینه که کسی اشتباها بیاد و یه آی دی رو تغییر بده. اینجوری باید یه روش باشه که بفهمیم و جلوش رو بگیریم. روش فعلی البته هنوز اینکار رو نمیکنه چون هنوز به id نهایی برای همه رویدادها نرسیدیم. ولی در کل موافقم نیاز به گو یا هر چیز دیگه ای رو برای ویرایشگر رویداد از بین ببریم. 

</div>

**Comment by okian** [comment]
چرا جنریت و تستش رو تراویس انجام نده؟

**Comment by fzerorubigd** [comment]
هدف همینه. تا زمانی که شناسه همه رویدادها اوکی نشن گذاشتن تست براش بیفایدست. چون فعلا داریم تغییرشون میدیم. تموم که شد اینکار رو میکنیم. - دست کم تقویم جلالی رو که تموم کردیم -

**Comment by fzerorubigd** [comment]
البته منطقا اگه کلا پوشه dist رو حذف کنیم از برنچ مستر مشکل حل میشه. چون پوش اتوماتیک روی مستر درست نیست، ولی روی برنچهای دیگه اوکیه.

**Comment by fzerorubigd** [comment]
الان میبینم که این خیلی مهمه :))) الان انجامش میدم
