### ISSUE TITLE
اصلاح عنوان رویداد فتح خرمشهر 

### ISSUE THREAD

**Issue by FaRzad-845** [persiancal/cal-events#53]
اصلاح     fa_IR: فتح خرمشهر در عملیات بیت‌المقدس (۱۳۶۱ ه‍.ش) و روز مقاومت، ایثار و پیروزی

https://github.com/persiancal/cal-events/pull/46#discussion_r330975887

**Comment by fzerorubigd** [comment]
Good catch :D Thank you.
