### ISSUE TITLE
استاندارد برای کامیت

### ISSUE THREAD

**Issue by hramezani** [persiancal/cal-events#59]
به نظرم خوبه که یه استاندارد برای کامیت ها در نظر بگیریم. قرار هم نیست خیلی دست و پا گیر باشه فقط برای یک دست شدن کامیت ها
نکته بعد اینکه بهتره کامیت های تو هر 
PR
رو ادغام کنیم و به عنوان یک کامیت به مستر اضافه بشه

**Comment by fzerorubigd** [comment]
از لحاظ تاریخچه من مشکلی نمیبینم که تاریخچه شلوغ باشه. 
از طرفی، هدف اینجا جامعه گیت بلد :)‌نیستن. خیلیا صرفا میخوان کمک کنن، و من نمیخوام بترسونیمشون. همین که همکاری کنن کافیه، اینکه یه نفری که کلا با گیت آشنایی نداره میاد اینجا و کامیت میکنه به نظر من خیلی با ارزشه. قصدم نداریم یادش بدیم شاید اصلا به دردش نخوره. 

ولی به نظرم یه سری قالب برای ایشو ها لازمه،‌خصوصا وقتی کسی میخواد مشکلی رو در مورد یه رویداد خاص گزارش بده.

**Comment by fzerorubigd** [comment]
برای این لازمه کار دیگه ای انجام بدیم @hramezani ؟

**Comment by hramezani** [comment]
فکر کنم میتونیم ببندیم این رو.
من هنوز معتقدم که هیستوری کامیت های ما خرابه. 
ولی توضیح تو راجع به اینکه همه گیت بلد نیستن و ما نمیخوایم کسانی رو که دارن مشارکت میکنن اذیت کنیم منو قانع کرد

ادغام کردن همه کامیت ها هم زمان مرج میتونه واقعا بعضی کامیت های که باید باشن رو از بین ببره.
اگه چیز دیگه ای به ذهنم رسید مطرح میکنم.

میتونیم ببنیدم این رو
