### ISSUE TITLE
 زمان شروع و پایان برای مناسبت‌ها تاریخی

### ISSUE THREAD

**Issue by behdad222** [persiancal/cal-events#6]
امیدوارم عنوان گمراه کننده نباشه
ایشویی به ما رسیده بود که مثلا ۱۲ فروردین قبل از انقلاب روز جمهوری اسلامی نبوده
ولی ما برای تمامی سال‌ها این مناسبت‌ها رو 
نمایش میدیم
خوبه که امکانی باشه که از چه تاریخی به بعد این مناسبت وجود داره، مثلا روز کارگر از یک سالی به بعد انتخاب شده. یا از چه تاریخی به بعد وجود نداره. به احتمال زیاد جشنی برای تولد ولیعهد قبل انقلاب بوده.
امکان نمایش مناسبت‌های همون زمان رو تو تاریخ مربوطه وجود داشته باشه

**Comment by fzerorubigd** [comment]
برای شروع فیلد 
Year 
هست ولی برای پایانش چیزی نیست. شاید اگه بر مبنای 
Type 
بگیم درست شه. یعنی برای سالهای قبل نیست، ولی برای سالهای بعد  در یک تقویم خاص (ایران پهلوی مثلا ) میذاریمش. اگه کسی اون تقویم رو خوند همچنان تو لیست خواهد بود ولی برای کسی که اون تقویم رو نخواد لزومی نداره که ببینتش.

**Comment by vahid-sohrabloo** [comment]
الزاما فقط  تایپ  نیست.
مثلا روز هسته‌ای از یک سال خاصی شروع میشه.
حتی بعضی از مناسبت‌ها هست که از یه تاریخ به قبل تعطیل بوده بعدش نبوده و حتی برعکس

**Comment by fzerorubigd** [comment]
درمورد شروع، گفتم که کلید 
year 
برای همین کاره، برای تعطیلی هم اگه ببینید یه کلید داره به اسم 
Iran 
که یه آرایست، و داخل آرایه قراره که شرایط اضافه بشه. مثلا اگه تعطیلی برای یک شهر بخصوصه، یا بعد از یه سالی بوده یا در یه سال به خصوصی حساب شده و این چیزا. منتها اینکه داخل اون آرایه رو چجوری قراره پر کنیم ایده ای ندارم

**Comment by fzerorubigd** [comment]
از نظر شما برای شروع مناسبت تاریخی چنین چیزی کافیه : 
https://github.com/fzerorubigd/cal-events/blob/master/jalali.yml#L30-L42

دقت کنید تو توضیح رویداد دیگه تاریخ نداریم ولی فیلد سال مقدار داره.

**Comment by dariubs** [comment]
بنظرم برای پایان هم خوبه یک فیلد در نظر گرفته بشه که در صورتی که نیاز بود ذکر بشه
مثلا یجایی روز گفتگوی تمدن ها از تقویم رسمی حذف شد :

https://www.bbc.com/persian/iran/2010/09/100921_l38_iran_calender_event

ولی خب تا یجایی تو تقویم معاصر بود.

**Comment by fzerorubigd** [comment]
برای پایان ایده اولیه من این بود که بذاریمش تو یه تایپ دیگه، ولی الان که
میبینم خیلی سخت میشه برای پیدا کردن رویداد در یه روز خاص از سالی که این
مناسبت هم در تقویم بوده، موافقم. اسم پیشنهاد بدین برای کلید مورد نظر.

**Comment by dariubs** [comment]
discontinue چطوره؟

**Comment by fzerorubigd** [comment]
برای این کلید هم تصمیم بگیریم و اضافش کنیم. 
discontinue 
خیلی سنگینه کلمش :)) یه کلمه ساده تر کسی نمیتونه بگه؟
