### ISSUE TITLE
ماه محرم، تقویم هجری قمری

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#66]
[مستندات](https://github.com/persiancal/cal-events/blob/master/docs/events.md) مربوط به کلیدهای رویداد را ببینید

و اگر سوالی داشتید هم برای اینکه یکجا باشد در ایشوی شماره #65 بپرسید

**Comment by fzerorubigd** [comment]
@srahnama اگه اینجا یه کامنت بذارید این ایشو رو اساین کنم به شما که دوباره کسی شروعش نکنه.

**Comment by srahnama** [comment]
@fzerorubigd 
ممنون
من روش کار میکنم
