### ISSUE TITLE
ماه صفر، تقویم هجری قمری

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#67]
[مستندات](https://github.com/persiancal/cal-events/blob/master/docs/events.md) مربوط به کلیدهای رویداد را ببینید

و اگر سوالی داشتید هم برای اینکه یکجا باشد در ایشوی شماره #65 بپرسید

**Comment by sbabashahi** [comment]
این ماه رو من انجام میدم

**Comment by fzerorubigd** [comment]
fixed in #95
