### ISSUE TITLE
Using JSON 

### ISSUE THREAD

**Issue by b00f** [persiancal/cal-events#7]
سوال ساده. چرا از جیسون برای اینکار استفاده نمی‌کنید. فکر کنم مشکلاتی که ذکر کردید را براحتی رفع کند. به زبان برنامه نویسی خاصی هم وابستگی ندارد.

**Comment by fzerorubigd** [comment]
مشکل اساسی 
json 
اینه که نمیشه کامنت زد داخلش، و مشکل دوم اینه که هدف قابل خوندن بودن فایل توسط آمیزاده نه کامپیوتر ،از طرفی این 
source of truth 
حساب میشه، و از روی این کلی فرمت دیگه همه ایجاد میشه. که همش رو کامیت خواهیم کرد تو یه پوشه داخل این مخزن.

**Comment by b00f** [comment]
> نمیشه کامنت زد داخلش

 عیب بزرگی نیست به نظر من

> هدف قابل خوندن بودن فایل توسط آمیزاده نه کامپیوتر 

 یکی از مزیتهای جیسون این است که قابل فهم برای آدمیزاد است. از طرفی کلی پارسر هست برای بهتر نمایش دادن جیسون

 > از روی این کلی فرمت دیگه همه ایجاد میشه

براحتی میشود جیسون را تبدیل کرد به فرمتهای دیگر.

 البته این نظر من است. بهتر بیشتر بحث بشود.

**Comment by fzerorubigd** [comment]
ممنون بابت پاسخ!
در مورد کامنت نظر شخصی منه که بودنش خیلی بهتر از نبودنشه.
در مورد قابل خوندن بودن هدف برنامه نویسها نیستن و من اینو تست کردم که خوندن
yaml
برای آدمی که برنامه نویسی نمیدونه راحت تره دوم اینکه میشه جیسون رو به صورت
خطی و در یک خط نوشت. هیچ گونه ایندنت گذاری رو محبور به انجامش نیستیم. برای
من برنامه نویس این مزیته، ولی برای مدیریت یه فایل بزرگ، برای یه مدت طولانی
نیست، چون اونوقت کلی باید بحث کنیم که چه ایندنتی رو بپذیریم و تب باشه یا
اسپیس، بعد ابزاری برای اینکه چک کنه پول ریکوئستها رو برای اینکه کسی تخطی
نکنه ازش باید بنویسیم یا پیدا کنیم. . ولی
yaml
ایندنت رو اجباری میکنه و شما نمیتونید طور دیگه ای بنویسیدش. بعدش کاراکتر
اضافه ای نداره، من طرفدارش نیستم اگه بحث کانفیگ و این چیزا باشه، ولی برای
دیتا سورس خواناتره.
در مورد فرمتهای دیگه، اونها هم بر اساس این فایل درست میشن تو یه فولدر به
اسم
dist
و یک تست خواهد بود که تست کنه اینها دقیقا برمبنای همین فایل ایحاد شدن و هیچ
گونه دستکاری انسانی صورت نگرفته توشون.
ولی همچنان بحث بازه، اگه دلایل من کافی نیستن، میتونید دلایل خودتون رو بگید.

**Comment by fzerorubigd** [comment]
اگر الان چک کنید، فایل با پسوند جیسون هم در مخزن وجود دارد. منتها این فایل بر مبنای فایل اصلی درست شده. هدف ساختن پسوندهای دیگر هم هست.

**Comment by b00f** [comment]
جیسون مثل یک چیز نیمه خام میماند و باید پخته شود. مثلا در مورد کامنت خیلی ساده میشود یک فیلد کامنت تعبیه کرد. تبدیل جیسون به فرمتهای دیگر بسیار ساده است و سادگی همیشه برنده است.

بگذریم. برای اینکه بحث دو طرفه نشود شما این بحث را باز بگذارید تا دیگران هم نظر بدهند. 
موفق باشید.
