### ISSUE TITLE
ماه جمادی‌الثانی، تقویم هجری قمری

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#71]
[مستندات](https://github.com/persiancal/cal-events/blob/master/docs/events.md) مربوط به کلیدهای رویداد را ببینید

و اگر سوالی داشتید هم برای اینکه یکجا باشد در ایشوی شماره #65 بپرسید

**Comment by hramezani** [comment]
این ماه رو من انجام میدم

**Comment by amin3mej** [comment]
فرودجان اگه امکانش هست، این رو به من اساین کن.

**Comment by okian** [comment]
merged #99
