### ISSUE TITLE
ماه رجب، تقویم هجری قمری

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#72]
[مستندات](https://github.com/persiancal/cal-events/blob/master/docs/events.md) مربوط به کلیدهای رویداد را ببینید

و اگر سوالی داشتید هم برای اینکه یکجا باشد در ایشوی شماره #65 بپرسید

**Comment by neda1985** [comment]
به من اساین میکنید لطفا

**Comment by hramezani** [comment]
[مستندات](https://github.com/persiancal/cal-events/blob/master/docs/events.md) مربوط به کلیدهای رویداد را ببینید

و اگر سوالی داشتید هم برای اینکه یکجا باشد در ایشوی شماره #65 بپرسید

**Comment by neda1985** [comment]
https://github.com/persiancal/cal-events/pull/92
مرسی اگه نگاه کنید

**Comment by fzerorubigd** [comment]
Fixed in #98
