### ISSUE TITLE
ماه شعبان، تقویم هجری قمری

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#73]
[مستندات](https://github.com/persiancal/cal-events/blob/master/docs/events.md) مربوط به کلیدهای رویداد را ببینید

و اگر سوالی داشتید هم برای اینکه یکجا باشد در ایشوی شماره #65 بپرسید

**Comment by tavallaie** [comment]
فرود جان این رو اساین کن به من

**Comment by fzerorubigd** [comment]
@tavallaie friendly ping :D

**Comment by tavallaie** [comment]
Thanks for ping, I need it :D

**Comment by fzerorubigd** [comment]
Fixed in #144
