### ISSUE TITLE
ماه شوال، تقویم هجری قمری

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#75]
[مستندات](https://github.com/persiancal/cal-events/blob/master/docs/events.md) مربوط به کلیدهای رویداد را ببینید

و اگر سوالی داشتید هم برای اینکه یکجا باشد در ایشوی شماره #65 بپرسید

**Comment by FaRzad-845** [comment]
اینم با من

**Comment by fzerorubigd** [comment]
@FaRzad-845 friendly ping :D

**Comment by hramezani** [comment]
Fixed in https://github.com/persiancal/cal-events/pull/160
