### ISSUE TITLE
ماه ذوالقعده، تقویم هجری قمری

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#76]
[مستندات](https://github.com/persiancal/cal-events/blob/master/docs/events.md) مربوط به کلیدهای رویداد را ببینید

و اگر سوالی داشتید هم برای اینکه یکجا باشد در ایشوی شماره #65 بپرسید

**Comment by Goudarz** [comment]
من اینو انجام میدم

**Comment by okian** [comment]
#105 مرج شد
