### ISSUE TITLE
ماه ذوالحجه، تقویم هجری قمری

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#77]
[مستندات](https://github.com/persiancal/cal-events/blob/master/docs/events.md) مربوط به کلیدهای رویداد را ببینید

و اگر سوالی داشتید هم برای اینکه یکجا باشد در ایشوی شماره #65 بپرسید

**Comment by 2hamed** [comment]
I'll take this one.

**Comment by fzerorubigd** [comment]
fixed in #94
