### ISSUE TITLE
پیشنهاد کلید جدید برای رویدادها

### ISSUE THREAD

**Issue by ahmadrezash** [persiancal/cal-events#82]
سلام
من چند تا کلید جدید می خوام برای رویداد ها پیشنهاد بدم
یکی کلید تعطیل رسمی بودن یا نبودن
یکی اولویت بندی مناسبت ها(البته این یه کم نسبیه) مثلا احتمالا اولویت ۲۲ بهمن بالاتر از شهادت نواب صفوی هستش یا حتی جشن خردادگان(منظورم در سطح جامعه س) برای این کار می تونیم با نظر سنجی عمومی هم این تکمیلش کنیم
یکی دیگه نوع مناسبت که مذهبی یا ملی یا سنتی یا مثلا برای کدون دینه یا ...
به نظرم این سه تا کلید مخصوصا کلید اول به درد می خوره برای کسایی که بعدا می خوان از این دیتاست استفاده کنن
باتشکر

**Comment by fzerorubigd** [comment]
> سلام
> من چند تا کلید جدید می خوام برای رویداد ها پیشنهاد بدم
> یکی کلید تعطیل رسمی بودن یا نبودن

کلید تعطیل رسمی بودن یا نبودن وجود داره به این صورت 
```yaml
holiday: 
  Iran : []
```
کلید به صورت یک مپ از اسم کشور به یک آرایه است. چرا آرایه؟ چون هدف اینه که بشه شرایط گذاشت برای تعطیلی ، مثلا اینکه در یک استان یا شهر خاص تعطیله -ایران نداریم چنین چیزی ولی در دنیا مرسومه-

> یکی اولویت بندی مناسبت ها(البته این یه کم نسبیه) مثلا احتمالا اولویت ۲۲ بهمن بالاتر از شهادت نواب صفوی هستش یا حتی جشن خردادگان(منظورم در سطح جامعه س) برای این کار می تونیم با نظر سنجی عمومی هم این تکمیلش کنیم

برای اولویت بندی بر اساس اهمیت، کاربردش چیه؟ چون من کاربردی نمیبینم شخصا. ولی اگه بتونید کاربردی براش معرفی کنید میشه به اضافه کردنش فکر کرد. 
از طرفی، این اطلاعات ، منبع دار هستن و قراره رفرنس باشن. وارد کردن یه دیتای بدون مبنا،به نظر من درست نیست. ما دیتا درست نمیکنیم اون رو جمع آوری و مدون میکنیم. 

> یکی دیگه نوع مناسبت که مذهبی یا ملی یا سنتی یا مثلا برای کدون دینه یا ...
> به نظرم این سه تا کلید مخصوصا کلید اول به درد می خوره برای کسایی که بعدا می خوان از این دیتاست استفاده کنن
> باتشکر

کلید تقویم هدف نهاییش همینه . الان رویدادهای ایران باستان و ایران - که در حقیقت جمهوری اسلامی ایرانه - رو از هم جدا کردیم. ولی این کلید هنوز جای بحث داره و اینکه چه مقادیری رو باید براش مجاز بدونیم و مبنای انتخاب یکی روی یک رویداد چیه

**Comment by fzerorubigd** [comment]
فکر میکنم الان تمام چیزهایی که اینجا پیشنهاد شده رو داریم. من ایشو رو میبندم، اگه فکر میکنید چیزی هست که هنوز اجرا نشده یا قابل بحثه، این ایشو رو مجددا باز کنید یا اینکه یه ایشوی جدید ایجاد کنید. متشکرم!
