### ISSUE TITLE
مبنای رویدادها در تقویم

### ISSUE THREAD

**Issue by okian** [persiancal/cal-events#9]
مبنای تقویم قرار هست به چه صورت انتخاب بشه؟ آیا رویدادها نسبت به یک تقویم مرجع ثبت می‌شوند یا هر رویدادی نسبت به تقویم خودش؟ مثلا روز عاشورا ۱۰ام محرم تقویم قمری است یا در سال ۱۳۹۸ شمسی روز ۱۹ام شهریور یا ۱۰ام سپتامبر  ۲۰۱۹ به عنوان روز عاشورای آن سال ثبت می‌شود؟

**Comment by fzerorubigd** [comment]
هر تقویم کاملا مجزا و نسبت به تقویم خودش سنجیده میشه. 
مثلا دهم محرم میشه عاشورا، این یه مناسبت تقویم قمری از سال ۶۱ هجریه، ولی توی تقویم شمسی نیست. زمانی که api نوشته میشه، بر مبنای روزی که توی تقویم درخواست میشه همون لحظه محاسبات انجام میشه و همه تقویمهای مورد نظر پر میشن.

**Comment by neda1985** [comment]
من یه سوالی دارم مرجع این دیتا ها باید کجا باشه؟

**Comment by fzerorubigd** [comment]
مرجع رسمی برای تقویم ایران به صورت پی دی اف اینجاست 

https://calendar.ut.ac.ir/Fa/TYear/Data/Full-1381.pdf

اون 81 رو عوض کنید سالهای بعدم میبینید. 
یک کلید سورس میخوامی اضافه کنیم به هر رویداد اینجوری 

```yaml
source:
- https://wikipedia/link/to/event/page
```

ولی مبنای تقویم جمهوری اسلامی ایران اون پی دی افه، ولی دلیلی نداره رویدادهای دیگه رو هم اضافه کنیم اگر که ویکی داشته باشن. یعنی سورس اعتبار سنجیمون ویکیپدیاست.

**Comment by hramezani** [comment]
باید حتما لینک ویکی پدیا مربوط به اون رویداد تو یه روز باشه یا راجع به مثلا شخصیت باشه هم باید اضافه بشه.؟
مثلا اول خرداد روز بزرگداشت ملاصدرا (صدرالمتألهین) هست. برای این روز باید حتما لینک ویکی مربوط به این ایونت رو گذاشت یا لینک ویکی ملاصدرا رو هم میشه گذاشت؟

**Comment by fzerorubigd** [comment]
source 
یک آرایست. بهتره اول لینک رویداد باشه بعد لینکهای مرتبط. یعنی اگه خود رویداد لینک مشخصی داره . اگه نداره لینک مرتبط کافیه. 

این نظر منه، ایشوی #1 هم دربارش کلی بحث شد.

**Comment by fzerorubigd** [comment]
@hramezani معذرت میخوام . الان که رفتم برای نوشتن تعیین اعتبار متوجه شدم که 
sources 
باید میگفتم، به صورت جمع.

**Comment by neda1985** [comment]
این تقویم ناقص خیلی کلا از سال ۸۱ به اونور و میاره :/ 
https://calendar.ut.ac.ir/Fa/TYear/Data/Full-1381.pdf
@fzerorubigd

**Comment by fzerorubigd** [comment]
فعلا برای گام اول صرفا به همین اکتفا میکنیم. چاره خاصی نداریم، برای ریلیز اول اگه بشه که همه رویدادها لینک ویکی داشته باشن فقط بعد باید بشینیم و یه فکری برای سورس معتبر و رسمی بکنیم.
